spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workstation_db
    username: workstation_server
    password: workstation_db_secret_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  data:
    rest:
      base-path: /api
    redis:
      host: localhost
      port: 6379
      cache:
        type: redis
        redis:
          time-to-live: 600000
  application:
    name: workstations
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
aes:
  key: secureAesKey1234567890123456

#logging:
#  level:
#    org.springframework: DEBUG
#    org.hibernate: DEBUG
